// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1mQQZCAsFbMSsPQy6U3-nyhV_KlZay50',
    appId: '1:1029042840828:web:2ede945bd7a187341e2379',
    messagingSenderId: '1029042840828',
    projectId: 'maximal-codex-424206-f2',
    authDomain: 'maximal-codex-424206-f2.firebaseapp.com',
    storageBucket: 'maximal-codex-424206-f2.appspot.com',
    measurementId: 'G-7QPH9864D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCACxsnHXwW0rXQRzB8T2m8CIajwkHuc7Y',
    appId: '1:1029042840828:android:8f0e833d0527bdbc1e2379',
    messagingSenderId: '1029042840828',
    projectId: 'maximal-codex-424206-f2',
    storageBucket: 'maximal-codex-424206-f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbgkwB7ct0oJidGpVCxKPBtLby2cY6mI4',
    appId: '1:1029042840828:ios:b2b150651cb246521e2379',
    messagingSenderId: '1029042840828',
    projectId: 'maximal-codex-424206-f2',
    storageBucket: 'maximal-codex-424206-f2.appspot.com',
    iosBundleId: 'com.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbgkwB7ct0oJidGpVCxKPBtLby2cY6mI4',
    appId: '1:1029042840828:ios:b2b150651cb246521e2379',
    messagingSenderId: '1029042840828',
    projectId: 'maximal-codex-424206-f2',
    storageBucket: 'maximal-codex-424206-f2.appspot.com',
    iosBundleId: 'com.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1mQQZCAsFbMSsPQy6U3-nyhV_KlZay50',
    appId: '1:1029042840828:web:6c892c5a1c9f58621e2379',
    messagingSenderId: '1029042840828',
    projectId: 'maximal-codex-424206-f2',
    authDomain: 'maximal-codex-424206-f2.firebaseapp.com',
    storageBucket: 'maximal-codex-424206-f2.appspot.com',
    measurementId: 'G-C0DMKLNGJ1',
  );

}